# permissions for end users to view canariedapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: canariedapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: canary-operator
    app.kubernetes.io/part-of: canary-operator
    app.kubernetes.io/managed-by: kustomize
  name: canariedapp-viewer-role
rules:
- apiGroups:
  - canary.cecg.io
  resources:
  - canariedapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - canary.cecg.io
  resources:
  - canariedapps/status
  verbs:
  - get
