{{- $namespace := print .Values.module "-autograding" -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-cluster-role-binding-{{ .Values.module }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io