apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: pushgateway-autograding
  labels:
    app.kubernetes.io/name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway
          ports:
            - containerPort: 9091