apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: pushgateway-autograding
spec:
  selector:
    app.kubernetes.io/name: pushgateway
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091