apiVersion: batch/v1
kind: Job
metadata:
  name: nft-obs-acceptance-tests
  namespace: nft-obs-autograding
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nft-obs-acceptance-tests
          image: nft-obs-acceptance-tests:latest
          imagePullPolicy: Never
