apiVersion: batch/v1
kind: Job
metadata:
  name: p2p-acceptance-tests
  namespace: p2p-autograding
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: p2p-acceptance-tests
          image: cecg/p2p-autograding
          imagePullPolicy: Never
