name: Autograding-nft-observability-CI

on:
  push:
    branches:
      - main
    paths:
      - "bootcamp-resources/autograding/nft-observability/**"

jobs:
  Push-NFT-Observability-Autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        working-directory: bootcamp-resources/autograding/nft-observability
        run: |
          make build-and-push