name: Autograding-P2P-CD

on:
  push:
    branches:
      - main
    paths:
      - "bootcamp-resources/autograding/p2p/**"

jobs:
  Push-P2P-Autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        working-directory: bootcamp-resources/autograding/p2p
        run: |
          make build-and-push