name: Dockerfiles

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string

jobs:
  dockerfiles:
    name: ${{ inputs.action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Dockerfiles
        id: dockerfiles-lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          recursive: true
