name: Get Artifacts Version

on:
  workflow_call:
    secrets:
      git_token:
        required: true
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    name: get-artifact-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Version
        id: getversion
        uses: ./.github/actions/get-version
        with:
          git-token: ${{ secrets.git_token }}
    outputs:
      version: ${{ steps.getversion.outputs.version }}
