name: Knowledge-platform-CI

on:
  push:
    branches:
      - main
    paths:
      - "knowledge-base/**"
  pull_request:
    branches:
      - main
    paths:
      - "knowledge-base/**"

jobs:
  get-version:
    name: get-version
    uses: ./.github/workflows/get-artifact-version.yaml
    secrets:
      git_token: ${{secrets.GITHUB_TOKEN}}  

  create-tag:
    name: create-tag
    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && vars.SHOULD_PUSH == 'true'
    needs: [get-version]
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        id: create_tag
        with:
          tag: v${{ needs.get-version.outputs.version }}
          tag_exists_error: true
  
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && vars.SHOULD_PUSH == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: knowledge-base/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cecg/knowledge-platform:latest

  repository-dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && vars.SHOULD_PUSH == 'false'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: coreeng/cecg-knowledge-platform-deployment
          event-type: dispatch-event
