name: Reference-app-go-CI

on:
  pull_request:
    branches:
      - main 
    paths:
      - "bootcamp-resources/modules/p2p/reference-application-go/**"
  push:
    branches:
      - main 
    paths:
      - "bootcamp-resources/modules/p2p/reference-application-go/**"

jobs:
  Stubbed-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        working-directory: bootcamp-resources/modules/p2p/reference-application-go
        run: |
          make build
      - name: Stubbed-Functional
        working-directory: bootcamp-resources/modules/p2p/reference-application-go
        env:
          SERVICE_ENDPOINT: 'http://service:8080'
        run: |
          make local-stubbed-functional
      - name: Stubbed-NFT
        working-directory: bootcamp-resources/modules/p2p/reference-application-go
        run: |
          make local-stubbed-nft
